name: Discord Webhook Notification

on:
  push:
    branches:
      - main # Change to your default branch

jobs:
  discord_notification:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord Webhook
        uses: actions/http-client@v2
        with:
          # We'll use curl directly
          run: |
            curl -H "Content-Type: application/json" \
            -X POST \
            -d "$(jq -n \
              --arg author "${{ github.actor }}" \
              --arg repo "${{ github.repository }}" \
              --arg branch "${{ github.ref_name }}" \
              --arg commit_msg "${{ github.event.head_commit.message }}" \
              --arg commit_url "${{ github.event.head_commit.url }}" \
              '{
                "embeds": [{
                  "title": "\($repo) | New Commit",
                  "description": "\($commit_msg)",
                  "url": "\($commit_url)",
                  "color": 3066993,
                  "footer": {
                    "text": "Committed by \($author) on branch \($branch)"
                  },
                  "timestamp": "'$(date -u +%Y-%m-%dT%H:%M:%SZ)'"
                }]
              }')" \
            ${{ secrets.DISCORD_WEBHOOK }}
